services:
  dev:
    extends:
      file: docker-compose.yml
      service: dev
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      # For remote graphics acceleration, no effect if not using VGL
      - VGL_DISPLAY=:0
      - VGL_COMPRESS=proxy
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
