name: build_and_test

on:
  push:
    tags:
      - '*'
    branches:
      - humble
      - jazzy
      - '*-devel'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - '*'
  workflow_dispatch:

# Do not run multiple jobs for the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      # NOTE: This will not work for non-public submodules. Use a token and config substitution instead.
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.event.repository.name }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
      # TODO: Use GHCR or Dockerhub to push images once these are public
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          target: er4-dev-source
          push: false
          load: true
          cache-from: type=gha,scope=ros-${{ github.event.repository.name }}
          cache-to: type=gha,mode=max,scope=ros-${{ github.event.repository.name }}
      - name: Run tests
        run: |
          docker run --rm \
            ${{ steps.meta.outputs.tags }} \
            bash -c "
              colcon test --executor sequential --packages-skip robotiq_driver clearpath_mecanum_drive_controller && \
              colcon test-result --verbose
            "
